### PR TITLE
fix: update packages to have a compatibility with typeorm 0.3.*

### LINKED ISSUE #189: [Feature request] Add support for typeorm ^0.3.0
Please add support for typeorm 0.3.0.

### PR DESCRIPTION
**Pull request by kevin-lot**
update packages, replace tslint with eslint, remove useless types packages

BREAKING CHANGE: Imcompatible with typeorm 0.2.0, this version uses the new datasource class of
typeorm 0.3.0.

fix #189

### CODE REVIEW

**Review by RobinCK — APPROVED** [review]

**Comment by RobinCK** [comment]
thanks @kevin-lot 
tests stopped working, I'll try to solve on the weekend

**Comment by kevin-lot** [comment]
python2 is not available on Alpine 3.16 that is the base of node:lts-alpine.

Only python3 can be installed.
https://pkgs.alpinelinux.org/packages?name=python*&branch=v3.15
https://pkgs.alpinelinux.org/packages?name=python*&branch=v3.16

**Comment by kevin-lot** [comment]
Maybe with an update of borales/actions-yarn to 3.0.0 [here](https://github.com/RobinCK/typeorm-fixtures/blob/4f08587501ff7d36748d3cecfc4c78397c8677b9/.github/workflows/build.yml#L27)

Diff of borales/actions-yarn between last and previous version: https://github.com/Borales/actions-yarn/compare/v2.3.0...v3.0.0#files_bucket

**Comment by kevin-lot** [comment]
@RobinCK I did that: https://github.com/RobinCK/typeorm-fixtures/pull/195

**Comment by RobinCK** [comment]
typeorm-fixtures-cli@2.0.0 released

**Pull request merged**
