### PR TITLE
Refactor from fork

### PR DESCRIPTION
**Pull request by kevin-lot**
I don't want to fork this package but the maintener should be really busy in this dark time. So, for now, I create this package https://www.npmjs.com/package/typeorm-fixtures-cli-fork.

When the maintener will have more time and this pull request merged, I will deprecate the fork.

 - Remove createConnection to use CommandUtils.loadDataSource(dataSourcePath).
 - Update some packages of package.json.
 - Update and configure new husky.
 - Use new fakerjs.
 - Use yargs instead of commander to have same library as typeorm.
 - Remove some JSDOC that are the same as type declarations of TypeScript
 - Replace substr by substring
 - Rework Builder class
 - Ignore __call method with ignorePrefix option of class-validator
 - Use actions/setup-node that contains yarn.
 - Update README.
 
 - Ignore decorator of class-validator
   Add a new option to ignoreDecorators or not.

### CODE REVIEW

**Comment by RobinCK** [comment]
@kevin-lot 
very nice changes, thank you very much

**Comment by RobinCK** [comment]
version 3.0.0 published

**Comment by kevin-lot** [comment]
@RobinCK Thank you.

I will do some changes in the future.
 - Add some info in the Readme.

In version 1 (and typeorm 0.3.0), I had an issue with lazy relation.
 - I have to do some tests with the new version.

**Comment by RobinCK** [comment]
Thank you for your contribution to the project.
I sent an invitation for you to the project because now I can't always allocate time for a quick PR review

**Pull request merged**
